// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZGpMY7oTHlBF5BdWyx8VdRgd1eCm5VA',
    appId: '1:187296690842:web:d8d6dc59d222ab2e50a523',
    messagingSenderId: '187296690842',
    projectId: 'weather-fairy-c552e',
    authDomain: 'weather-fairy-c552e.firebaseapp.com',
    storageBucket: 'weather-fairy-c552e.appspot.com',
    measurementId: 'G-7K773SX4W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkrdRw_o6vIbgu0_LYlkzwWX9qeKLYy8I',
    appId: '1:187296690842:android:d18995ee6126018650a523',
    messagingSenderId: '187296690842',
    projectId: 'weather-fairy-c552e',
    storageBucket: 'weather-fairy-c552e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBngnvQHkHeJVfFdOLlN7BOXLwgZYC0ys',
    appId: '1:187296690842:ios:c56aa9edf878ab3250a523',
    messagingSenderId: '187296690842',
    projectId: 'weather-fairy-c552e',
    storageBucket: 'weather-fairy-c552e.appspot.com',
    iosClientId: '187296690842-d4qi4ltno3atfcqsac0poh2ii0a16f9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherFairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBngnvQHkHeJVfFdOLlN7BOXLwgZYC0ys',
    appId: '1:187296690842:ios:22d23dcb442b870450a523',
    messagingSenderId: '187296690842',
    projectId: 'weather-fairy-c552e',
    storageBucket: 'weather-fairy-c552e.appspot.com',
    iosClientId: '187296690842-mjjp3stepu9dq2tdh99ttogeu4sh3216.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherFairy.RunnerTests',
  );
}
